[package]
name = "pacpin"
version = "3.2.0-alpha.1"
edition = "2021"
authors = ["Gyan <330976822+gyanhavingsyntropy@users.noreply.github.com>"]
description = "Declarative Package Resolver & Upgrade Engine for Arch Linux / CachyOS"
license = "GPL-3.0-or-later"

[dependencies]
alpm = "5.0.2"
ureq = { version = "2.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
colored = "2.1"
glob = "0.3"
terminal_size = "0.4.4"
crossterm = "0.28"
libc = "0.2"
tar = "0.4"
ctrlc = { version = "3.4", features = ["termination"] }
